hmcts/ccd-next-hearing-date-updater

charts/ccd-next-hearing-date-updater/Chart.yaml
charts/ccd-next-hearing-date-updater/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/CCD-4401
CCD-4401 : Update elasticsearch chart to 7.17.3
```
[ ] Yes
[X] No
```

CCD-4401 : Update elasticsearch chart to 7.17.3

---

build.gradle

Added pitest

---

build.gradle

Upgraded sonarqube

---

build.gradle

Upgrade befta

---

.github/renovate.json
Jenkinsfile_CNP

NA
Fix nightly build - deprecated renovate config
```
[ ] Yes
[X] No
```

fix nightly build

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4454
bumped snakeyaml to 2.0, removed suppression
```
[ ] Yes
[X] No
```

CCD-4454 : Fix-CVE-2022-1471

---

charts/ccd-next-hearing-date-updater/Chart.yaml

NA
bump chart job to 1.1.5
```
[ ] Yes
[X] No
```

Fix master pipeline -> bump chart job to 1.1.5

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4736
Removing https://github.com/advisories/GHSA-xf96-w227-r7c4 suppression and bumping to the next minor version change.
```
[ ] Yes
[x] No
```

Removing suppression and bumping packages

---

charts/ccd-next-hearing-date-updater/Chart.yaml

CCD-5133  Update Chart.yaml

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5076
CVE-2023-33202 : Bump spring-security-rsa
```
[ ] Yes
[ x] No
```

CVE-2023-33202 : Bump spring-security-rsa

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5201
Updated Spring Security version to resolve CVE
```
[ ] Yes
[X] No
```

CCD-5201 Resolved Spring Security CVE

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/functionalTest/java/uk/gov/hmcts/reform/next/hearing/date/updater/befta/ServiceBeftaRunner.java

https://tools.hmcts.net/jira/browse/CCD-5362
Befta-fw 9.0.2, ccd-test-definitions 7.22.2, gradle 8.7
```
[ ] Yes
[ x] No
```

Befta-fw 9.0.2, ccd-test-definitions 7.22.2, gradle 8.7

---

build.gradle
config/owasp/suppressions.xml

CCD-5311 Fix CVE-2023-20873

---

src/integrationTest/java/uk/gov/hmcts/reform/next/hearing/date/updater/CcdCaseEventServiceIT.java
src/main/java/uk/gov/hmcts/reform/next/hearing/date/updater/service/CcdCaseEventService.java

https://tools.hmcts.net/jira/browse/CCD-5181
Handle null nextHearingDetails value + test
```
[ ] Yes
[x ] No
```

CCD-5181 : Handle null nextHearingDetails value

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5196
Resolved CVE 6481 but rep scan gives a couple of small other CVEs so resolved as part of this story.
```
[ ] Yes
[x] No
```

CCD-5265 CVE fixes 260324

---

Jenkinsfile_CNP
build.gradle
gradle/wrapper/gradle-wrapper.properties

NA
Attempt to fix current error in stage pitest (mutation tests) in the nightly pipeline:
INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 65
```
[ ] Yes
[X] No
```

Fix pitest failure in nitghtly pipeline

---

charts/ccd-next-hearing-date-updater/Chart.yaml
charts/ccd-next-hearing-date-updater/values.yaml
lib/applicationinsights.json

Fix initialisation of App Insights, which should resolve an issue with the app not shutting down correctly and marking the job as failed.
```
[ ] Yes
[x] No
```

Fix shutdown issues

---

Dockerfile

Add `applicationinsights.json` to Dockerfile

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5923
Bumped jackson
```
[ ] Yes
[X] No
```

CCD 5923: fix CVE 2023 35116

---

build.gradle
config/owasp/suppressions.xml

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/CCD-4975
https://tools.hmcts.net/jira/browse/CCD-4373
Change description
Fix https://github.com/advisories/GHSA-4jq9-2xhw-jpx7 across all Java Repos
https://github.com/advisories/GHSA-3vqj-43w4-2q58 - All CCD Java repos
```
[ ] Yes
[x] No
```

CCD-4975&CCD-4373

---

charts/ccd-next-hearing-date-updater/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update base chart versions

---

Jenkinsfile_CNP
build.gradle
charts/ccd-next-hearing-date-updater/Chart.yaml
charts/ccd-next-hearing-date-updater/values.preview.template.yaml
charts/ccd-next-hearing-date-updater/values.yaml
settings.gradle

https://tools.hmcts.net/jira/browse/CCD-6456
```
[ ] Yes
[ ] No
```

CCD-6456 update to oci
